openapi: 3.0.0
info:
  title: Luminous API
  version: 1.0.0
  description: API documentation for Luminous

servers:
  - url: https://{tenantName}.luminous.com/external/api/v1
    variables:
      tenantName:
        default: companyname
        description: The tenant-specific subdomain

paths:
  /purchase-orders:
    get:
      summary: Retrieve purchase orders
      description: Get a paginated list of purchase orders
      security:
        - BearerAuth: []
      parameters:
        - in: query
          name: page
          schema:
            type: integer
            default: 1
          description: Page number for pagination
        - in: query
          name: per_page
          schema:
            type: integer
            default: 10
          description: Number of items per page
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    type: array
                    items:
                      $ref: '#/components/schemas/PurchaseOrder'
                  meta:
                    $ref: '#/components/schemas/PaginationMeta'
        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

components:
  schemas:
    PurchaseOrder:
      type: object
      properties:
        id:
          type: integer
        order_date:
          type: string
          format: date
        status:
          type: string
          enum: [active, completed, deleted]

    PaginationMeta:
      type: object
      properties:
        current_page:
          type: integer
        from:
          type: integer
        last_page:
          type: integer
        path:
          type: string
        per_page:
          type: integer
        to:
          type: integer
        total:
          type: integer

    Error:
      type: object
      properties:
        message:
          type: string

  securitySchemes:
    BearerAuth:
      type: http
      scheme: bearer
      description: Authenticate using a bearer token. To obtain a token, contact the Luminous support team.