type: object
properties:
  id:
    type: integer
  name:
    type: string
  description:
    type: string
  icon:
    type: string
  color:
    type: string
  discount_structure:
    type: object
  markup_structure:
    type: object