type: object
properties:
  id:
    type: integer
    description: Unique identifier for the product
  name:
    type: string
    description: Product name
  description:
    type: string
    nullable: true
    description: Product description
  retail_price:
    type: number
    format: float
    description: Retail price
  wholesale_price:
    type: number
    format: float
    description: Wholesale price
  unit_cost:
    type: number
    format: float
    description: Cost per unit
  product_weight:
    type: number
    format: float
    description: Weight of the product
  product_length:
    type: number
    format: float
    description: Length of the product
  product_width:
    type: number
    format: float
    description: Width of the product
  product_height:
    type: number
    format: float
    description: Height of the product
  box_weight:
    type: string
    nullable: true
    description: Weight of the box
  box_length:
    type: number
    format: float
    nullable: true
    description: Length of the box
  box_width:
    type: number
    format: float
    nullable: true
    description: Width of the box
  box_height:
    type: number
    format: float
    nullable: true
    description: Height of the box
  carton_weight:
    type: string
    nullable: true
    description: Weight of the carton
  carton_length:
    type: number
    format: float
    nullable: true
    description: Length of the carton
  carton_width:
    type: number
    format: float
    nullable: true
    description: Width of the carton
  carton_height:
    type: number
    format: float
    nullable: true
    description: Height of the carton
  shipping_weight:
    type: string
    nullable: true
    description: Shipping weight
  shipping_length:
    type: number
    format: float
    nullable: true
    description: Shipping length
  shipping_width:
    type: number
    format: float
    nullable: true
    description: Shipping width
  shipping_height:
    type: number
    format: float
    nullable: true
    description: Shipping height
  pallet_weight:
    type: string
    nullable: true
    description: Weight of the pallet
  pallet_length:
    type: number
    format: float
    nullable: true
    description: Length of the pallet
  pallet_width:
    type: number
    format: float
    nullable: true
    description: Width of the pallet
  pallet_height:
    type: number
    format: float
    nullable: true
    description: Height of the pallet
  sellable:
    type: boolean
    description: Whether the product can be sold
  discontinued:
    type: boolean
    description: Whether the product is discontinued. Discontinued products will be hidden in the Luminous UI by default.
  image_url:
    type: string
    nullable: true
    description: URL to the product's main image
  category:
    type: object
    nullable: true
    properties:
      id:
        type: integer
      name:
        type: string
    description: Product category information
  subcategory:
    type: object
    nullable: true
    properties:
      id:
        type: integer
      name:
        type: string
    description: Product subcategory information
  custom_fields:
    type: object
    description: Dynamic custom fields with key-value pairs
    additionalProperties:
      type: string
  attachments:
    type: array
    description: Product attachments
    items:
      $ref: './attachment.yaml'
  variants:
    type: array
    description: Product variants
    items:
      type: object
      properties:
        id:
          type: integer
        name:
          type: string
        description:
          type: string
          nullable: true
        attachments:
          type: array
          description: Variant-specific attachments
          items:
            $ref: './attachment.yaml'
        retail_price:
          type: number
          format: float
        wholesale_price:
          type: number
          format: float
        custom_fields:
          type: array
          items:
            type: object
        variant_attributes:
          type: object
          additionalProperties:
            type: string
        sku:
          type: string
        upc:
          type: string
        created_at:
          type: string
          format: date-time
        updated_at:
          type: string
          format: date-time
  variant_attributes:
    type: object
    nullable: true
    description: Available variant attributes
  sku:
    type: string
    description: Internal SKU
  alternate_skus:
    type: array
    description: Alternate SKUs
    items:
      type: object
      properties:
        id:
          type: integer
        sku:
          type: string
  upc:
    type: string
    description: UPC/Barcode
  tags:
    type: array
    description: Tags associated with the product
    items:
      $ref: './tag.yaml'
  substitutions:
    type: array
    description: Product substitutions, these products may be substituted if the main product is out of stock
    items:
      type: object
      properties:
        id:
          type: integer
          description: Substitution record ID
        priority:
          type: integer
          description: Substitution priority (lower number = higher priority)
        product:
          type: object
          description: The substitute product
          properties:
            id:
              type: integer
              description: Unique identifier for the product
            name:
              type: string
              description: Product name
            description:
              type: string
              nullable: true
              description: Product description
            retail_price:
              type: number
              format: float
              description: Retail price
            wholesale_price:
              type: number
              format: float
              description: Wholesale price
            unit_cost:
              type: number
              format: float
              description: Cost per unit
            product_weight:
              type: number
              format: float
              description: Weight of the product
            product_length:
              type: number
              format: float
              description: Length of the product
            product_width:
              type: number
              format: float
              description: Width of the product
            product_height:
              type: number
              format: float
              description: Height of the product
            box_weight:
              type: string
              nullable: true
              description: Weight of the box
            box_length:
              type: number
              format: float
              nullable: true
              description: Length of the box
            box_width:
              type: number
              format: float
              nullable: true
              description: Width of the box
            box_height:
              type: number
              format: float
              nullable: true
              description: Height of the box
            carton_weight:
              type: string
              nullable: true
              description: Weight of the carton
            carton_length:
              type: number
              format: float
              nullable: true
              description: Length of the carton
            carton_width:
              type: number
              format: float
              nullable: true
              description: Width of the carton
            carton_height:
              type: number
              format: float
              nullable: true
              description: Height of the carton
            shipping_weight:
              type: string
              nullable: true
              description: Shipping weight
            shipping_length:
              type: number
              format: float
              nullable: true
              description: Shipping length
            shipping_width:
              type: number
              format: float
              nullable: true
              description: Shipping width
            shipping_height:
              type: number
              format: float
              nullable: true
              description: Shipping height
            pallet_weight:
              type: string
              nullable: true
              description: Weight of the pallet
            pallet_length:
              type: number
              format: float
              nullable: true
              description: Length of the pallet
            pallet_width:
              type: number
              format: float
              nullable: true
              description: Width of the pallet
            pallet_height:
              type: number
              format: float
              nullable: true
              description: Height of the pallet
            sellable:
              type: boolean
              description: Whether the product can be sold
            discontinued:
              type: boolean
              description: Whether the product is discontinued
            image_url:
              type: string
              nullable: true
              description: URL to the product's main image
            sku:
              type: string
              description: Internal SKU
            upc:
              type: string
              description: UPC/Barcode
            created_at:
              type: string
              format: date-time
              description: Timestamp when the product was created
            updated_at:
              type: string
              format: date-time
              description: Timestamp when the product was last updated
  supplier:
    type: object
    nullable: true
    description: Supplier information
  type:
    type: string
    enum: [PRODUCT, KIT]
    description: Product type. PRODUCT for regular products, KIT for kit products that contain other products as components.
  kit_items:
    type: array
    nullable: true
    description: Kit items (components) for kit products. Only present when type = KIT.
    items:
      type: object
      properties:
        id:
          type: integer
          description: Unique identifier for the kit item
        product_id:
          type: integer
          description: ID of the product component
        quantity:
          type: number
          format: float
          description: Quantity of this component in the kit
        uom_id:
          type: integer
          description: Unit of measure ID for the quantity
        base_uom_quantity:
          type: number
          format: float
          description: Quantity converted to base unit of measure
        price:
          type: number
          format: float
          description: Price for this kit item
        original_price:
          type: number
          format: float
          description: Original price for this kit item
        total:
          type: number
          format: float
          description: Calculated total (quantity * price)
        product:
          type: object
          nullable: true
          description: Product information for this kit item (when loaded)
          properties:
            id:
              type: integer
            name:
              type: string
            sku:
              type: string
            description:
              type: string
              nullable: true
            retail_price:
              type: number
              format: float
            wholesale_price:
              type: number
              format: float
        unit_of_measure:
          type: object
          nullable: true
          description: Unit of measure information (when loaded)
          properties:
            id:
              type: integer
            name:
              type: string
            description:
              type: string
              nullable: true
            base_unit:
              type: boolean
  boms:
    type: array
    description: BOMs (Bills of Materials) associated with this product
    items:
      $ref: './bom.yaml'
  created_at:
    type: string
    format: date-time
    description: Timestamp when the product was created
  updated_at:
    type: string
    format: date-time
    description: Timestamp when the product was last updated