type: object
properties:
  name:
    type: string
    maxLength: 200
    description: Product name
  category_id:
    type: integer
    description: ID of the product category
  category:
    type: object
    nullable: true
    properties:
      name:
        type: string
        description: Name of the product category. If the category is not found in Luminous, it will be created.
    description: Product category information
  sku:
    type: string
    maxLength: 100
    description: Internal SKU
  qty_low_alert:
    type: integer
    nullable: true
    description: Quantity threshold for low stock alerts
  qty_reorder_threshold:
    type: integer
    nullable: true
    description: Quantity threshold for reordering
  qty_minimum:
    type: integer
    nullable: true
    description: Minimum quantity to maintain
  supplier_id:
    type: integer
    nullable: true
    description: ID of the preferred supplier
  supplier:
    type: object
    nullable: true
    properties:
      name:
        type: string
        description: Name of the preferred supplier. If the supplier is not found in Luminous, it will be created.
    description: Product preferred supplier information
  image_url:
    type: string
    maxLength: 255
    nullable: true
    description: URL to product image
  sellable:
    type: boolean
    nullable: true
    description: Whether the product can be sold
  lot_tracking:
    type: boolean
    nullable: true
    description: Whether to track product by lots
  sub_category_id:
    type: integer
    nullable: true
    description: ID of the product subcategory
  subcategory:
    type: object
    nullable: true
    properties:
      name:
        type: string
        description: Name of the product sub-category. If the sub-category is not found in Luminous, it will be created.
    description: Product sub-category information
  default_receiving_location_id:
    type: integer
    nullable: true
    description: Default location ID for receiving this product
  description:
    type: string
    nullable: true
    description: Product description
  wholesale_price:
    type: number
    format: float
    minimum: 0
    nullable: true
    description: Wholesale price
  retail_price:
    type: number
    format: float
    minimum: 0
    nullable: true
    description: Retail price
  unit_cost:
    type: number
    format: float
    minimum: 0
    nullable: true
    description: Cost per unit
  product_weight:
    $ref: './weight-value.yaml'
  dimensional_weight:
    $ref: './weight-value.yaml'
  product_length:
    type: number
    format: float
    minimum: 0
    nullable: true
    description: Length of the product (in inches)
  product_width:
    type: number
    format: float
    minimum: 0
    nullable: true
    description: Width of the product (in inches)
  product_height:
    type: number
    format: float
    minimum: 0
    nullable: true
    description: Height of the product (in inches)
  box_weight:
    $ref: './weight-value.yaml'
  box_length:
    type: number
    format: float
    minimum: 0
    nullable: true
    description: Length of the box (in inches)
  box_width:
    type: number
    format: float
    minimum: 0
    nullable: true
    description: Width of the box (in inches)
  box_height:
    type: number
    format: float
    minimum: 0
    nullable: true
    description: Height of the box (in inches)
  carton_weight:
    $ref: './weight-value.yaml'
  carton_length:
    type: number
    format: float
    minimum: 0
    nullable: true
    description: Length of the carton (in inches)
  carton_width:
    type: number
    format: float
    minimum: 0
    nullable: true
    description: Width of the carton (in inches)
  carton_height:
    type: number
    format: float
    minimum: 0
    nullable: true
    description: Height of the carton (in inches)
  shipping_weight:
    $ref: './weight-value.yaml'
  shipping_length:
    type: number
    format: float
    minimum: 0
    nullable: true
    description: Shipping length (in inches)
  shipping_width:
    type: number
    format: float
    minimum: 0
    nullable: true
    description: Shipping width (in inches)
  shipping_height:
    type: number
    format: float
    minimum: 0
    nullable: true
    description: Shipping height (in inches)
  pallet_weight:
    $ref: './weight-value.yaml'
  pallet_length:
    type: number
    format: float
    minimum: 0
    nullable: true
    description: Length of the pallet (in inches)
  pallet_width:
    type: number
    format: float
    minimum: 0
    nullable: true
    description: Width of the pallet (in inches)
  pallet_height:
    type: number
    format: float
    minimum: 0
    nullable: true
    description: Height of the pallet (in inches)
  upc:
    type: string
    nullable: true
    description: UPC/Barcode
  custom_fields:
    type: object
    nullable: true
    description: Custom field values
    additionalProperties:
      type: string
  tags:
    type: array
    nullable: true
    description: Tags to associate with the product
    items:
      type: string
  variants:
    type: array
    nullable: true
    description: Product variants
    items:
      type: object
      required:
        - sku
      properties:
        name:
          type: string
          maxLength: 200
          description: Variant name
        sku:
          type: string
          maxLength: 100
          description: Variant SKU
        image_url:
          type: string
          maxLength: 255
          nullable: true
          description: URL to variant image
        qty_low_alert:
          type: integer
          nullable: true
          description: Quantity threshold for low stock alerts
        qty_reorder_threshold:
          type: integer
          nullable: true
          description: Quantity threshold for reordering
        qty_minimum:
          type: integer
          nullable: true
          description: Minimum quantity to maintain
        supplier_id:
          type: integer
          nullable: true
          description: ID of the variant's preferred supplier
        supplier:
          type: object
          nullable: true
          properties:
            name:
              type: string
              description: Name of the preferred supplier. If the supplier is not found in Luminous, it will be created.
          description: Product preferred supplier information
        sellable:
          type: boolean
          nullable: true
          description: Whether the variant can be sold
        discontinued:
          type: boolean
          nullable: true
          description: If an item is discontinued it will be hidden by default in the Luminous UI
        default_receiving_location_id:
          type: integer
          nullable: true
          description: Default location ID for receiving this variant
        description:
          type: string
          nullable: true
          description: Variant description
        wholesale_price:
          type: number
          format: float
          minimum: 0
          nullable: true
          description: Variant wholesale price
        retail_price:
          type: number
          format: float
          minimum: 0
          nullable: true
          description: Variant retail price
        unit_cost:
          type: number
          format: float
          minimum: 0
          nullable: true
          description: Variant cost per unit
        product_weight:
          $ref: './weight-value.yaml'
        dimensional_weight:
          $ref: './weight-value.yaml'
        product_length:
          type: number
          format: float
          minimum: 0
          nullable: true
          description: Length of the variant (in inches)
        product_width:
          type: number
          format: float
          minimum: 0
          nullable: true
          description: Width of the variant (in inches)
        product_height:
          type: number
          format: float
          minimum: 0
          nullable: true
          description: Height of the variant (in inches)
        box_weight:
          $ref: './weight-value.yaml'
        box_length:
          type: number
          format: float
          minimum: 0
          nullable: true
          description: Length of the box (in inches)
        box_width:
          type: number
          format: float
          minimum: 0
          nullable: true
          description: Width of the box (in inches)
        box_height:
          type: number
          format: float
          minimum: 0
          nullable: true
          description: Height of the box (in inches)
        carton_weight:
          $ref: './weight-value.yaml'
        carton_length:
          type: number
          format: float
          minimum: 0
          nullable: true
          description: Length of the carton (in inches)
        carton_width:
          type: number
          format: float
          minimum: 0
          nullable: true
          description: Width of the carton (in inches)
        carton_height:
          type: number
          format: float
          minimum: 0
          nullable: true
          description: Height of the carton (in inches)
        shipping_weight:
          $ref: './weight-value.yaml'
        shipping_length:
          type: number
          format: float
          minimum: 0
          nullable: true
          description: Shipping length (in inches)
        shipping_width:
          type: number
          format: float
          minimum: 0
          nullable: true
          description: Shipping width (in inches)
        shipping_height:
          type: number
          format: float
          minimum: 0
          nullable: true
          description: Shipping height (in inches)
        pallet_weight:
          $ref: './weight-value.yaml'
        pallet_length:
          type: number
          format: float
          minimum: 0
          nullable: true
          description: Length of the pallet (in inches)
        pallet_width:
          type: number
          format: float
          minimum: 0
          nullable: true
          description: Width of the pallet (in inches)
        pallet_height:
          type: number
          format: float
          minimum: 0
          nullable: true
          description: Height of the pallet (in inches)
        upc:
          type: string
          nullable: true
          description: Variant UPC/Barcode
        custom_fields:
          type: object
          nullable: true
          description: Custom field values for the variant
          additionalProperties:
            type: string
        tags:
          type: array
          nullable: true
          description: Tags to associate with the variant
          items:
            type: string
  boms:
    type: array
    nullable: true
    description: |
      Array of BOM IDs to attach to the product. If null or empty array, all BOMs will be detached.
      When updating, this will replace all existing BOM associations.
    items:
      type: integer
      description: BOM ID