openapi: 3.0.0
info:
  title: Luminous API
  version: 1.0.0
  description: API documentation for Luminous

servers:
  - url: https://{companyName}.api.joinluminous.com/external/api/v1
    variables:
      companyName:
        default: companyName
        description: Your company-specific subdomain

components:
  securitySchemes:
    BearerAuth:
      type: http
      scheme: bearer
      description: Authenticate using a bearer token. To obtain a token, contact developers@joinluminous.com

paths:
  /products:
    $ref: './products.yaml'
  /products/{id}:
    $ref: './product.yaml'
  /purchase-orders:
    $ref: './purchase-orders.yaml'
  /purchase-orders/{id}:
    $ref: './purchase-order.yaml'
  /inventory/adjustments:
    $ref: './inventory-adjustments.yaml'
  /inventory/stocks:
    $ref: './inventory-stocks.yaml'
  /transfer-orders:
    $ref: './transfer-orders.yaml'
  /transfer-orders/{id}:
    $ref: './transfer-order.yaml'
  /receiving-reports:
    $ref: './receiving-reports.yaml'
  /receiving-reports/{id}:
    $ref: './receiving-report.yaml'
  /sales-orders:
    $ref: './sales-orders.yaml'
  /sales-orders/{id}:
    $ref: './sales-order.yaml'
  /sales-orders/{salesOrderId}/shipments:
    $ref: './sales-order-shipments.yaml'
  /invoices:
    $ref: './invoices.yaml'
  /invoices/{id}:
    $ref: './invoice.yaml'
  /{recordType}/{recordId}/tags:
    $ref: './tags.yaml'
  /{recordType}/{recordId}/tags/{id}:
    $ref: './tag.yaml'
  /{recordType}/{recordId}/custom-fields:
    $ref: './custom-fields.yaml'

tags:
  - name: Products
    description: Get and manage products
  - name: Purchase Orders
    description: Get and modify purchase orders
  - name: Inventory
    description: Get and adjust product stock levels
  - name: Transfer Orders
    description: Manage transfer orders
  - name: Receiving Reports
    description: Manage receiving reports
  - name: Sales Orders
    description: Manage sales orders and sales order shipments
  - name: Invoices
    description: Get and manage invoices
  - name: Tags
    description: Add/remove tags across various resources
  - name: Custom Fields
    description: Get and set custom fields across various resources