openapi: 3.0.0
info:
  title: Luminous API
  version: 1.0.0
  description: API documentation for Luminous

servers:
  - url: https://{companyName}.api.joinluminous.com/external/api/v1
    variables:
      companyName:
        default: companyName
        description: Your company-specific subdomain

components:
  securitySchemes:
    BearerAuth:
      type: http
      scheme: bearer
      description: Authenticate using a bearer token. To obtain a token, contact developers@joinluminous.com

paths:
  /products:
    $ref: './products.yaml'
  /products/{id}:
    $ref: './product.yaml'
  /products/pricing:
    $ref: './products-pricing.yaml'
  /products/{productId}/pricing:
    $ref: './product-pricing.yaml'
  /purchase-orders:
    $ref: './purchase-orders.yaml'
  /purchase-orders/{id}:
    $ref: './purchase-order.yaml'
  /inventory/adjustments:
    $ref: './inventory-adjustments.yaml'
  /inventory/stocks:
    $ref: './inventory-stocks.yaml'
  /transfer-orders:
    $ref: './transfer-orders.yaml'
  /transfer-orders/{id}:
    $ref: './transfer-order.yaml'
  /receiving-reports:
    $ref: './receiving-reports.yaml'
  /receiving-reports/{id}:
    $ref: './receiving-report.yaml'
  /sales-orders:
    $ref: './sales-orders.yaml'
  /sales-orders/{id}:
    $ref: './sales-order.yaml'
  /sales-orders/{salesOrderId}/shipments:
    $ref: './sales-order-shipments.yaml'
  /sales-orders/{salesOrderId}/shipments/{shipmentId}/packages:
    $ref: './sales-order-shipment-packages.yaml'
  /invoices:
    $ref: './invoices.yaml'
  /invoices/{id}:
    $ref: './invoice.yaml'
  /{recordType}/{recordId}/tags:
    $ref: './tags.yaml'
  /{recordType}/{recordId}/tags/{id}:
    $ref: './tag.yaml'
  /{recordType}/{recordId}/custom-fields:
    $ref: './custom-fields.yaml'
  /warehouses:
    $ref: './warehouses.yaml'
  /warehouses/{warehouseId}:
    $ref: './warehouse.yaml'
  /locations:
    $ref: './locations.yaml'
  /locations/{locationId}:
    $ref: './location.yaml'
  /companies:
    $ref: './companies.yaml'
  /companies/{companyId}:
    $ref: './company.yaml'
  /companies/{companyId}/contacts:
    $ref: './company-contacts.yaml'
  /companies/{companyId}/product-price-overrides:
    $ref: './company-product-price-overrides.yaml'
  /companies/{companyId}/products:
    $ref: './company-products.yaml'
  /contacts:
    $ref: './contacts.yaml'
  /price-schedules:
    $ref: './price-schedules.yaml'
  /price-schedules/{scheduleId}:
    $ref: './price-schedule.yaml'
  /price-levels:
    $ref: './price-levels.yaml'
  /price-levels/{levelId}:
    $ref: './price-level.yaml'

tags:
  - name: Locations
    description: Manage warehouses and locations
  - name: Products
    description: Get and manage products
  - name: Purchase Orders
    description: Get and modify purchase orders
  - name: Inventory
    description: Get and adjust product stock levels
  - name: Transfer Orders
    description: Manage transfer orders
  - name: Receiving Reports
    description: Manage receiving reports
  - name: Sales Orders
    description: Manage sales orders and sales order shipments
  - name: Invoices
    description: Get and manage invoices
  - name: Tags
    description: Add/remove tags across various resources
  - name: Custom Fields
    description: Get and set custom fields across various resources
  - name: Companies
    description: Manage business accounts and their associated data
  - name: Contacts
    description: Manage contact information for individuals
  - name: Pricing
    description: Manage price schedules, levels, and customizations