get:
  operationId: getSingleProductPricing
  tags:
    - Products
    - Pricing
  summary: Single product pricing
  description: |
    Retrieve comprehensive pricing information for a specific product, including base price, 
    pricing tiers, price levels, and any company-specific pricing overrides.
    
    This endpoint returns detailed pricing information that shows volume-based pricing tiers
    across different price levels as configured in the product's pricing schedule.
  security:
    - BearerAuth: []
  parameters:
    - name: productId
      in: path
      required: true
      schema:
        type: string
      description: The unique identifier of the product
  responses:
    '200':
      description: Detailed pricing information for the product
      content:
        application/json:
          schema:
            $ref: './components/product-pricing-detail.yaml'
    '401':
      $ref: './components/responses/unauthorized.yaml'
    '403':
      $ref: './components/responses/forbidden.yaml'
    '404':
      $ref: './components/responses/not-found.yaml' 