get:
  operationId: getProducts
  tags:
    - Products
  summary: Products
  description: |
    Get a paginated list of products with optional filtering.
    
    For detailed information about the filtering system and available operators, 
    refer to the [Filter System Documentation](/filters).

    ## Available Filters
    ### String Filters
    - `name`: Product name
    - `description`: Product description
    - `sku`: Product SKU (searches both internal SKU and alternate SKUs)
    - `upc`: Product UPC/Barcode
    - `tag`: Product tags
    - `q`: General search matches name OR upc OR sku
    - `category.name`: Filter by category name
    - `sub_category.name`: Filter by sub-category name
    - `supplier.name`: Filter by supplier name
    
    ### Integer Filters
    - `category.id`: Filter by category ID
    - `sub_category.id`: Filter by sub-category ID
    - `supplier.id`: Filter by supplier ID
    - `bom.id`: Filter by Bill of Materials ID (returns products attached to the specified BOM)
    - `kit_items.product_id`: Filter by kit item product ID (returns kit products that contain the specified product as a component)
    
    ### Enum Filters
    - `type`: Filter by product type (PRODUCT or KIT)
    
    ### Float Filters
    - `retail_price`: Product retail price
    - `wholesale_price`: Product wholesale price
    - `product_weight`: Product weight
    - `product_length`: Product length
    - `product_width`: Product width
    - `product_height`: Product height
    - `box_length`: Box length
    - `box_width`: Box width
    - `box_height`: Box height
    - `carton_length`: Carton length
    - `carton_width`: Carton width
    - `carton_height`: Carton height
    - `shipping_length`: Shipping length
    - `shipping_width`: Shipping width
    - `shipping_height`: Shipping height
    - `pallet_length`: Pallet length
    - `pallet_width`: Pallet width
    - `pallet_height`: Pallet height
    
    ### String Filters (Dimension Weights)
    - `box_weight`: Box weight
    - `carton_weight`: Carton weight
    - `shipping_weight`: Shipping weight
    - `pallet_weight`: Pallet weight
    
    ### Boolean Filters
    - `sellable`: If the product is sellable or not
    - `discontinued`: If the product is discontinued
    
    ### DateTime Filters
    - `created_at`: When the product was created
    - `updated_at`: When the product was last updated
    
    ## Examples
    ```
    # Find products by SKU (includes alternate SKUs)
    ?sku[eq]=SKU-001

    # Find products with specific price range
    ?retail_price[gte]=50.00&retail_price[lte]=100.00

    # Find recently updated products
    ?updated_at[gte]=2024-01-01 00:00:00

    # Search products by name
    ?name[contains]=Test Product
    
    # Find products by category and sub-category
    ?category.name[eq]=Electronics&sub_category.name[eq]=Smartphones
    
    # Find products by supplier
    ?supplier.name[contains]=Acme
    
    # Find products by type
    ?type=PRODUCT
    ?type=KIT
    
    # Find kit products that contain a specific product as a component
    ?kit_items.product_id=123
    
    # Find products by dimension filters
    ?product_length[gt]=10.0&product_width[lt]=20.0
    ?box_length[eq]=12.5
    ?carton_height[gte]=10.0
    ?shipping_length[lte]=18.0
    ?pallet_width[gt]=40.0
    ```
  security:
    - BearerAuth: []
  parameters:
    - in: query
      name: page
      schema:
        type: integer
        default: 1
      description: Page number for pagination
    - in: query
      name: per_page
      schema:
        type: integer
        default: 10
        maximum: 100
      description: Number of items per page (max 100)
    - in: query
      name: q
      schema:
        type: string
      description: Filter by name OR upc OR sku
    - in: query
      name: name
      schema:
        type: string
      description: Filter by product name
    - in: query
      name: description
      schema:
        type: string
      description: Filter by product description
    - in: query
      name: sku
      schema:
        type: string
      description: Filter by SKU (searches both internal and alternate SKUs)
    - in: query
      name: upc
      schema:
        type: string
      description: Filter by UPC/Barcode
    - in: query
      name: sellable
      schema:
        type: boolean
      description: Filter by sellable status
    - in: query
      name: discontinued
      schema:
        type: boolean
      description: Filter by whether the product is discontinued
    - in: query
      name: retail_price
      schema:
        type: number
        format: float
      description: Filter by retail price
    - in: query
      name: wholesale_price
      schema:
        type: number
        format: float
      description: Filter by wholesale price
    - in: query
      name: created_at
      schema:
        type: string
        format: date-time
      description: Filter by creation date
    - in: query
      name: updated_at
      schema:
        type: string
        format: date-time
      description: Filter by last update date
    - in: query
      name: tag
      schema:
        type: string
      description: Filter by product tags
    - in: query
      name: category.id
      schema:
        type: integer
      description: Filter by category ID
    - in: query
      name: category.name
      schema:
        type: string
      description: Filter by category name
    - in: query
      name: sub_category.id
      schema:
        type: integer
      description: Filter by sub-category ID
    - in: query
      name: sub_category.name
      schema:
        type: string
      description: Filter by sub-category name
    - in: query
      name: supplier.id
      schema:
        type: integer
      description: Filter by supplier ID
    - in: query
      name: supplier.name
      schema:
        type: string
      description: Filter by supplier name
    - in: query
      name: bom.id
      schema:
        type: integer
      description: Filter by Bill of Materials ID (returns products attached to the specified BOM)
    - in: query
      name: kit_items.product_id
      schema:
        type: integer
      description: Filter by kit item product ID (returns kit products that contain the specified product as a component)
    - in: query
      name: type
      schema:
        type: string
        enum: [PRODUCT, KIT]
      description: Filter by product type (PRODUCT for regular products, KIT for kit products)
    - in: query
      name: product_weight
      schema:
        type: number
        format: float
      description: Filter by product weight
    - in: query
      name: product_length
      schema:
        type: number
        format: float
      description: Filter by product length
    - in: query
      name: product_width
      schema:
        type: number
        format: float
      description: Filter by product width
    - in: query
      name: product_height
      schema:
        type: number
        format: float
      description: Filter by product height
    - in: query
      name: box_weight
      schema:
        type: string
      description: Filter by box weight
    - in: query
      name: box_length
      schema:
        type: number
        format: float
      description: Filter by box length
    - in: query
      name: box_width
      schema:
        type: number
        format: float
      description: Filter by box width
    - in: query
      name: box_height
      schema:
        type: number
        format: float
      description: Filter by box height
    - in: query
      name: carton_weight
      schema:
        type: string
      description: Filter by carton weight
    - in: query
      name: carton_length
      schema:
        type: number
        format: float
      description: Filter by carton length
    - in: query
      name: carton_width
      schema:
        type: number
        format: float
      description: Filter by carton width
    - in: query
      name: carton_height
      schema:
        type: number
        format: float
      description: Filter by carton height
    - in: query
      name: shipping_weight
      schema:
        type: string
      description: Filter by shipping weight
    - in: query
      name: shipping_length
      schema:
        type: number
        format: float
      description: Filter by shipping length
    - in: query
      name: shipping_width
      schema:
        type: number
        format: float
      description: Filter by shipping width
    - in: query
      name: shipping_height
      schema:
        type: number
        format: float
      description: Filter by shipping height
    - in: query
      name: pallet_weight
      schema:
        type: string
      description: Filter by pallet weight
    - in: query
      name: pallet_length
      schema:
        type: number
        format: float
      description: Filter by pallet length
    - in: query
      name: pallet_width
      schema:
        type: number
        format: float
      description: Filter by pallet width
    - in: query
      name: pallet_height
      schema:
        type: number
        format: float
      description: Filter by pallet height
  responses:
    '200':
      description: Successful response
      content:
        application/json:
          schema:
            type: object
            properties:
              data:
                type: array
                items:
                  $ref: './components/product.yaml'
              meta:
                $ref: './components/pagination-meta.yaml'
    '401':
      description: Unauthorized
      content:
        application/json:
          schema:
            $ref: './components/error.yaml'

post:
  operationId: createProduct
  tags:
    - Products
  summary: Create a product
  description: |
    Create a new product with optional variants, custom fields, and tags.
    
    **Kit Products:**
    When creating a kit product (type = KIT), the `kit_items` field is required and must contain at least one kit item.
    Each kit item must specify either `product_id` or `sku`, along with a `quantity`.
  security:
    - BearerAuth: []
  requestBody:
    required: true
    content:
      application/json:
        schema:
          $ref: './components/product-create.yaml'
  responses:
    '200':
      description: Successful response
      content:
        application/json:
          schema:
            type: object
            properties:
              data:
                $ref: './components/product.yaml'
    '409':
      description: Conflict - SKU already exists
      content:
        application/json:
          schema:
            $ref: './components/error.yaml'
    '422':
      description: Validation error
      content:
        application/json:
          schema:
            $ref: './components/validation-error.yaml'
    '401':
      description: Unauthorized
      content:
        application/json:
          schema:
            $ref: './components/error.yaml'
patch:
  operationId: createOrUpdateProduct
  tags:
    - Products
  summary: Create or update product
  description: Create a new product or update an existing one by SKU or ID
  security:
    - BearerAuth: []
  requestBody:
    required: true
    content:
      application/json:
        schema:
          allOf:
            - $ref: './components/product-update.yaml'
            - type: object
              properties:
                id:
                  type: integer
                  description: Product ID (required if SKU not provided)
                sku:
                  type: string
                  description: Product SKU (required if ID not provided)
              oneOf:
                - required: [id]
                - required: [sku]
  responses:
    '200':
      description: Successful response
      content:
        application/json:
          schema:
            type: object
            properties:
              data:
                $ref: './components/product.yaml'
    '422':
      description: Validation error
      content:
        application/json:
          schema:
            $ref: './components/validation-error.yaml'
    '401':
      description: Unauthorized
      content:
        application/json:
          schema:
            $ref: './components/error.yaml'