type: object
properties:
  id:
    type: string
    description: Unique identifier for the price override
    example: "987654"
  created_at:
    type: string
    format: date-time
    description: When the price override was created
    example: "2023-03-15T14:30:00Z"
  updated_at:
    type: string
    format: date-time
    description: When the price override was last updated
    example: "2023-03-15T14:30:00Z"
  status:
    type: string
    description: Status of the price override record
    enum: [active, inactive, deleted]
    example: "active"
  company_id:
    type: string
    description: ID of the company this price override applies to
    example: "123456"
  product_id:
    type: string
    description: ID of the product being overridden
    example: "567890"
  price:
    type: number
    format: float
    description: The override price for this product when sold to this company
    example: 42.50
  product:
    $ref: './price-override-product.yaml' 